### ISSUE TITLE
변수명을 성의있게 작성합시다.

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#10]
https://github.com/xfrnk2/1d1c/blob/94a67fd33a787c273b2c3aff59e3ac3a0a1b5b7a/hackerrank/Problem_Solving/Plus_Minus.py#L12

변수 a, b, c가 무슨 용도로 사용되고 있죠?
그 의미 자체를 반영하도록 변수 이름을 짓습니다.

예를 들어 positive, negative, zero_value 등...

**Comment by xfrnk2** [comment]
감사합니다.. 반영했어요

**Comment by zrma** [comment]
@xfrnk2 Good!
