### ISSUE TITLE
테스트가 또 실패하는군요.

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#100]
@xfrnk2 

lint 실패하고 있어요~
flake8 설정을 변경해서 한 줄의 최대 길이를 120으로 조절하는 건 어때요?

그리고 커밋 하기 전에
```bash
make test
make lint
```
이 두개를 꼭 해 줍시다.

참고로 `Makefile` 내부의 명령어들을 실행하는 프로그램은 `make`이고
make의 설치는 `scoop`을 이용해서 
```bash
scoop install make
```

scoop은 윈도우용 패키지 관리자입니다.
https://scoop.sh 참고!

그리고 아마 내 저장소에서 fork 해 간 Makefile은 윈도우에서는 동작하지 않을거에요.

1) 윈도우에서도 올바르게 동작하도록 수정하거나
2) 이 참에 리눅스에도 익숙해질 겸 WSL(Windows sub-system Linux)을 써 보세요.

**Comment by xfrnk2** [comment]
잘 지내시나요? 오랜만에 코멘트 드려요. 제가 한동안 한군데서 막혀서 진행을 못하고 있는데 도저히 해결이 안되서 여쭤보고 싶은데요,  터미널에 'make test'를 입력하면 make (e=5) : 액세스가 거부되었습니다. 라는 에러가 나오는데 구글링한 방법대로 만져봐도 고치질 못했어요.
뭐가 문제인지 모르겠네요..
make lint 역시 같은 에러가 뜹니다 ㅠㅠ

**Comment by zrma** [comment]
@xfrnk2 

> 그리고 아마 내 저장소에서 fork 해 간 Makefile은 윈도우에서는 동작하지 않을거에요.
> 1. 윈도우에서도 올바르게 동작하도록 수정하거나
> 2. 이 참에 리눅스에도 익숙해질 겸 WSL(Windows sub-system Linux)을 써 보세요.

제가 본문에 적었는데 제대로 안 읽으셨네요.

`VENV ?= . env/bin/activate`

이 부분에서 `. env/bin/activate`
이건 리눅스용 명령어고 윈도우용 venv 실행 명령어는 예전에 다 가르쳐 드렸는데 
복습도 안 하시고 요새 다 잊어버리셨나보네요.

저 부분을 윈도우용으로 수정해야 합니다.

세상 공부가 다 똑같겠지만, 프로그래밍은 일신우일신이 정말 중요합니다.
지금처럼 하면 언제 실력을 쌓아서 이쪽 관련 일을 하겠나요?

우형 테크캠프 지원하고, 코딩 문제 풀고, 떨어졌을 때를 떠올려 보세요.

**Comment by xfrnk2** [comment]
전과 같은말씀 하게 해드려서 죄송해요. 또 같은 우를 범해서..
최근 지병이 도졌었는데 건강이 흔들릴때가 제일로 속상하네요. 다시 흐름을 잡고 꾸준히 해 나아가볼게요. 바른 말씀 해주셔서 고맙습니다.

**Comment by xfrnk2** [comment]
@zrma  . venv/Scripts/activate.bat 으로 수정했는데 cmd 상에서는 여전히 같은 에러가 나오는데 (make (e=5) : 액세스가 거부되었습니다.)
Ubuntu상에서 make test를 입력해도  Can't open . venv/Scripts/activate.bat 이라고 나오네요.

make test를 Ubuntu상에서 입력해야 할까요? 어떻게 하는게 맞는건지 모르겠어요.. 
(어디서는 cmd에서 입력하면 된다는 이야기도 있고..)

1. 윈도우에서도 올바르게 동작하도록 수정하거나
2. 이 참에 리눅스에도 익숙해질 겸 WSL(Windows sub-system Linux)을 써 보세요.

2번과 같이 WSL을 사용하려고 Ubuntu를 설치해서 해당 경로에 가서 make test를 입력했는데 잘못 하고 있는걸까요?

**Comment by zrma** [comment]
@xfrnk2 

`make bootstrap` 이라고 먼저 실행하세요.

해당 과정을 통해 가상 환경 설정을 해야 합니다.

그리고 윈도우일 경우 맨 앞의 . 가 빠져야 합니다.

`. env/bin/activate` 이건 리눅스 용이고
`Scripts\activate.bat` 이건 윈도우 용이죠

윈도우에는 맨 앞에 . 찍는 명령이 없습니다.

**Comment by xfrnk2** [comment]
@zrma
넵 감사합니다
말씀해주신대로 하고 나니 Travi-Ci의 Job Log에 make test에 의한 pytest 기록이 생겼어요.

make test와 make lint를 실행했을때 그 기록은 어디에 남게 되나요?
그리고 make lint의 기록은 Travi-Ci의 Job Log에서 확인할 수 없는데 어디서 볼 수 있을까요?

**Comment by xfrnk2** [comment]
@zrma 
그리고 make 는 어디에서 돌아가는걸까요? 만약 PC에서 돌아가는거라면  사용후 제거 해야하는게 아닐까요? 어디서 어떻게 움직이는 것인지 흐름을 알고싶어요.
(+makefile내의 clean관련된 명령어들은 실행을 해도 지정된 파일을 찾을수 없다고 나오는데 어떤 기능들인가요?)

**Comment by zrma** [comment]
@xfrnk2 

1. travis-ci 는 .travis.yml 파일을 설정하는 것만으로 travis-ci 서버에서 동작합니다.
.travis.yml 파일에 서술한 대로 동작합니다.

> make test와 make lint를 실행했을때 그 기록은 어디에 남게 되나요?
> 그리고 make lint의 기록은 Travi-Ci의 Job Log에서 확인할 수 없는데 어디서 볼 수 있을까요?

`make test` 또는 `make lint`는 로컬에서 실행할 경우 표준 출력으로 확인할 수 있습니다.

* test  
test가 성공한다면 coverage가 뜰 것이고, 실패하면 실패한 테스트와 그 결과가 출력 되겠죠.
그러려면 우선 테스트 코드를 적절히 생성해야 하고요.

* lint  
pep8 파이썬 코딩 컨벤션을 지키지 않은 코드가 있을 경우 make lint 실행하면 실패하게 되고,  
해당 실패 내역이 표준 출력으로 나올 겁니다.

2. make 는 scoop 으로 설치했다면 윈도우에서 돌아갈 것이고, 
WSL에서 실행한다면 우분투(리눅스)에는 기본 내장 되어 있으니 거기서 돌아가겠죠.  
travis-ci (서버) 하고는 또 별개의 이야기입니다.

만약 `make test` 또는 `make lint`, 또는 `make_install` 했다면 
로컬에 egg 파일이나 기타 파일이 생기는 것을 볼 수 있는데(setup.py 동작에 의해),
`make clean`을 통해 이런 파일들을 제거할 수 있습니다.

**Comment by xfrnk2** [comment]
@zrma 명쾌한 설명 감사합니다!

**Comment by zrma** [comment]
@xfrnk2 travis-ci가 정상적으로 빌드 되고 있으니 해당 이슈는 닫을게요.
