### ISSUE TITLE
max 사용하기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#102]
https://github.com/xfrnk2/1d1c/blob/e2e3830be282f1f22af1bb50f3b2ec15cb96494c/hackerrank/Problem_Solving/Equalize_The_Array.py#L16

`max_value = max(max_value, value)`

**Comment by xfrnk2** [comment]
감사합니다!

**Comment by zrma** [comment]
@xfrnk2 수정 확인했어요~
