### ISSUE TITLE
sum 함수를 사용하세요.

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#11]
https://github.com/xfrnk2/1d1c/blob/94a67fd33a787c273b2c3aff59e3ac3a0a1b5b7a/hackerrank/Problem_Solving/simple_array_sum.py#L55

파이썬에는 sum() 함수가 있습니다.

reduce를 이해하고 사용해 본 것은 좋습니다.
reduce는 조금 더 복잡한 형태의 컨테이너 원소 취합 로직에 사용합시다.

**Comment by xfrnk2** [comment]
네 감사합니다~

**Comment by zrma** [comment]
@xfrnk2 Good!
