### ISSUE TITLE
travis-ci 일부 실패

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#118]
https://github.com/xfrnk2/1d1c/blob/e67e993384600b7b53f8d3e37a860e3677e107ae/Makefile#L8

travis-ci 로그를 살펴보면 
> /bin/sh: 1: ..venvScriptsactivate.bat: not found

이런 오류가 남고 있네요.

리눅스일 경우와 윈도우일 경우 스크립트가 달라져야 합니다.
make test 에서 실행하는 명령어를 별도 스크립트로 만든 후에
윈도우/리눅스 겸용 스크립트로 만들어 보세요.

힌트 : https://stackoverflow.com/questions/17510688/

**Comment by xfrnk2** [comment]
주말동안 연수가 있어서 다녀와서 계속할게요. 감사합니다

**Comment by zrma** [comment]
@xfrnk2 

I checked your master ci succeeded continously.
Good job.
