### ISSUE TITLE
pop() 함수는 꺼낸 요소를 반환합니다.

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#12]
https://github.com/xfrnk2/1d1c/blob/94a67fd33a787c273b2c3aff59e3ac3a0a1b5b7a/hackerrank/Arrays/Left_Lotation.py#L12

```python
temp = a[0]
a.pop(0)
a.append(temp)
```

이 세 줄의 코드를
```python
a.append(pop(0))
```
이렇게 바꾸면 됩니다.

**Comment by xfrnk2** [comment]
감사합니다.. 반영했어요

**Comment by zrma** [comment]
@xfrnk2 

https://github.com/xfrnk2/1d1c/blob/db4de95ebc891951080cfd513a85b55d04377518/hackerrank/Arrays/Left_Lotation.py#L11

a의 길이가 1일 경우, 루프 구문이 필요할까요?
a의 길이가 10인데 d의 값이 1조 쯤 된다면, 1조번 루프를 돌 필요가 있을까요?

**Comment by xfrnk2** [comment]
말씀의 요지에 가까운지 아닌지는 잘 모르겠지만, 처음부터 제한을 두는 방법으로 바꿔봤어요.

def rotLeft(a, d):
    size = len(a)
    if size <= 1 or not 1 <= d <= size:
        print("Wrong Input")
        exit()

    for _ in range(d):
        a.append(a.pop(0))
    return a

**Comment by zrma** [comment]
@xfrnk2 아뇨 문제를 다시 읽어보세요.

문제의 요구사항에 따르면 매우 큰 값도 들어올 수 있고, 그런 값을 정확히 처리해야 합니다.
제한을 두면 안 됩니다.

대신 효율적으로 풀어야죠.

**Comment by xfrnk2** [comment]
말씀하신것 참고해서 좀 바꿔봤어요.

    size = len(a)
    if size <= 1:
        pass
    if size < d:
        print("Wrong Input")
        exit()
    else:
        temp = a[:d]
        a = a[d:]
        a.extend(temp)
        values = ' '.join(str(v) for v in a)
    return a

**Comment by zrma** [comment]
@xfrnk2 아니라니까요. 문제를 다시 읽어보세요.

size < d 일 경우도 정상적인 입력입니다.
길이 5인 문자열을 100억번 회전시키는 것도 정상적인 요구사항이에요.

에러로 처리하면 안 됩니다.
그리고 길이 5인 문자열을 100억번 회전시키는 건 비효율적인 일이죠.
100억 1번 회전시킨다면? 100억 2번 회전시킨다면?

**Comment by xfrnk2** [comment]
감사합니다. 저는 제약사향(Constrants)의 
1 <= d <= n (n은 a의 길이)
이 라인을 많이 의식했었는데 말씀하시는게 뭔지 조금은 알 것 같아요.
이렇게 바꾸면 어떨까요?

def rotLeft(a, d):
    size = len(a)
    d = d % size
    
    if size <= 1:
        pass
    else:
        temp = a[:d]
        a = a[d:]
        a.extend(temp)
    return a

**Comment by zrma** [comment]
@xfrnk2 네 그런 의미가 맞아요.

```python
size = len(a)

# 리스트의 원소가 단 1개이면 의미가 없으므로 그냥 반환.
if size == 1:
    return a

# d >= size 에 대한 방어코드
d = d % size

# d == 0일 경우 회전이 의미가 없으므로 그냥 반환.
if d == 0:
    return a

return a[d:] + a[:d]
 ```

대충 이 정도를 원했습니다.
방어 코드 + 논리적으로 빠뜨린게 없는지 + 효율성

어떤 문제를 풀었다면, 풀고 바로 넘어가지 말고 그 이후에 다시 곰곰히 더 훑어보면 좋을 것 같아요.

**Comment by xfrnk2** [comment]
넵 감사합니다
