### ISSUE TITLE
else 제거

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#121]
https://github.com/xfrnk2/1d1c/blob/7bacc7c123df1399c358066cbf7240378b38a432/hackerrank/Problem_Solving/The_Time_In_Words.py#L27

‘’’
if m % 15 != 0:
        v = " minute"
        if 1 < m <= 60:
            v += "s"
        minutes += v
‘’’

**Comment by xfrnk2** [comment]
감사합니다! 수정했어요.

**Comment by zrma** [comment]
@xfrnk2 good!
