### ISSUE TITLE
제한 카운트를 초과하면 여기서 바로 반환해도 될 것 같습니다.

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#13]
https://github.com/xfrnk2/1d1c/blob/94a67fd33a787c273b2c3aff59e3ac3a0a1b5b7a/hackerrank/Arrays/New_Year_Chaos.py#L26

스왑 카운트를 모두 취합한 후에 다시 한 번 루프 돌지 말고,
제한 카운트 초과하면 바로 여기서 `Too chaotic`을 출력하고 끝내면 안 되나요?

**Comment by xfrnk2** [comment]
그러네요.. 감사합니다~

**Comment by zrma** [comment]
@xfrnk2 Good!
