### ISSUE TITLE
sonarqube badge 링크 정리

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#155]
@xfrnk2 

README.md 파일에 있는 badge 중에 sonarqube 경로가 [내 프로젝트](https://github.com/zrma/tdd)로 되어 있네요. 

바꿔주세요.

**Comment by xfrnk2** [comment]
@zrma 네 감사합니다. 수정했어요!

**Comment by zrma** [comment]
@xfrnk2 sonarqube 쪽에서 확인해보면 코드 퀄리티 문제가 여럿 발견 됩니다.
꾸준히 수정 해 보세요.
