### ISSUE TITLE
Initialize by zero

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#168]
https://github.com/xfrnk2/1d1c/blob/c6b8a56fc5bc8e4ea6da5ac060da3fe8e590f769/src/hackerrank/Problem_Solving/Ice_Cream_Parlor.py#L2

int 타입과 연산 할 건데 `None` 보다는 `0`이 좋겠어요

**Comment by xfrnk2** [comment]
감사합니다! 수정했어요.

**Comment by zrma** [comment]
@xfrnk2 확인했어요.
