### ISSUE TITLE
탈출 조건 확인

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#178]
https://github.com/xfrnk2/1d1c/blob/29b01111d0713f3a6c2a2fa93221b852abe259da/src/hackerrank/Problem_Solving/Ice_Cream_Parlor.py#L11

@xfrnk2 

> if j == b_value:

만약 이 조건을 만족하지 않으면 이 함수는 뭘 반환하죠?

**Comment by xfrnk2** [comment]
@zrma 아! 반환값이 없었네요...
아래처럼 수정했어요.

`def icecreamParlor(m, arr):
    a_value = b_value = 0
    answer = 0

    for i, j in enumerate(arr):
        if (m - j) in arr[i+1:]:
            b_value = m - j
            a_value = i
            continue

        if j == b_value:
            b_value = i
            answer = a_value+1, b_value+1
            break

    return answer`

**Comment by zrma** [comment]
@xfrnk2 아직 push 안 되었네요.

**Comment by xfrnk2** [comment]
@zrma 지금 했습니다!

**Comment by zrma** [comment]
@xfrnk2 

for 구문 중간에서 반환하면 반환 타입은 튜플인데 
for 구문 밖에서 반환할 때는 int 타입이네요?

반환 타입 불일치는 좋은 코드가 아닙니다.

**Comment by xfrnk2** [comment]
@zrma 앗.. 감사합니다. 수정했어요!

**Comment by zrma** [comment]
@xfrnk2 확인했어요.
