### ISSUE TITLE
unnecessary code

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#179]
https://github.com/xfrnk2/1d1c/blob/0ab610fb89884b44750ee5dfe8e3bcc226a9ac3d/tests/Alternating_Characters_test.py#L4

@xfrnk2 필요한가요?

**Comment by xfrnk2** [comment]
@zrma 
잘 모르겠네요;;.. 전상대경로로만 설정하면 터미널에서 pytest 실행 했을때 부모 모듈을 찾을수 없다는 에러가 나타나요..
 'from ..src.hackerrank.Problem_Solving.Jumping_On_The_Clouds_Revisited import jumping_on_clouds'  이렇게 바꿨어요.

**Comment by xfrnk2** [comment]
@zrma
 절대경로로 설정을 생략하고 상대경로로만 설정하면 터미널에서 pytest 실행 했을때 부모 모듈을 찾을수 없다는 에러가 나타나요..
'from ..src.hackerrank.Problem_Solving.Jumping_On_The_Clouds_Revisited import jumping_on_clouds' 이렇게 바꿨는데 에러가 나네요.

`ImportError: attempted relative import `

**Comment by xfrnk2** [comment]
@zrma 구글링 해보니 상대경로로도 설정하는 방법이 있어서 그대로 해보니 적용은 잘 되었는데...

https://blog.doosikbae.com/52 참고했어요.
`if __package__ is None:
    print(path.dirname( path.dirname( path.abspath(__file__) ) ))
    sys.path.append(path.dirname( path.dirname( path.abspath(__file__) ) ))
    from src.hackerrank.Problem_Solving.Jumping_On_The_Clouds_Revisited import jumping_on_clouds
else:
    from ..src.hackerrank.Problem_Solving.Jumping_On_The_Clouds_Revisited import jumping_on_clouds`

더 좋은 방법이 있을까요?

**Comment by zrma** [comment]
@xfrnk2 제 저장소 다시 한 번 확인 해 보세요.

https://wikidocs.net/1418 이것도 잘 정독하세요.

**Comment by xfrnk2** [comment]
@zrma 
감사합니다! 시원하게 해결되었어요.
tests 폴더 내의 *_test.py 파일이 있는 경로~ 패키지로 인식 시키려고 하는 최상위 디렉토리의 경로까지 __init__.py 파일을 추가했어요.

**Comment by zrma** [comment]
@xfrnk2 

```
import os
import sys
```

아직 이 두 import 안 지웠네요. 정리 ㄱㄱ

**Comment by zrma** [comment]
@xfrnk2 그리고 중간에 뭘 잘못 push 했는지 추가 된 `__init__.py` 파일이 전부 사라졌나? 안 보이네요?

**Comment by xfrnk2** [comment]
@zrma 

모두 지웠습니다!

도반님 저장소를 보니 __init__.py 파일이 폴더 대부분에 들어가 있는 것을 보고 무분별하게 따라했는데
정확히 어디에 __init__.py 파일이 필요한지만 알기 위해서 나머지는 모두 지운 상태에요. 
필요하다고 생각되는 곳에만 만들어두었어요.

**Comment by xfrnk2** [comment]
@zrma 
그리고 이건 이슈와는 관계 없는 질문이지만.. 질문 드리고 싶어서 잠시 남길게요.
해커랭크의 이 문제를 풀다가..
https://www.hackerrank.com/challenges/cavity-map/problem?h_r=internal-search

아래의 코드에서  'str' object does not support item assignment' 에러가 나오는데, 리스트 내의 문자열 값을 대입할수 없는것 같아 구글링&stackoverflow를 찾아서 할수 있는 만큼 해봤는데 뾰족한 방법을 찾기가 어려워서요. 어떻게 만드는게 좋을까요?

`    if len(grid) <= 2 or len(grid[0]) <= 2:
        return grid

    box = []
    x_value = grid[1:-1]
    target = 0

    for x in x_value:
        box.extend(x[1:-1])
    target = max(box)

    for x in range(1, len(grid) - 1):
        for y in range(1, len(grid[x]) - 1):

            if grid[x][y] == target:
                pass   # <- 이 부분입니다. grid[x][y] = "X" 로 문자열을 대입하려고 하니 위와 같은 에러가 발생해요.
    return grid`

**Comment by zrma** [comment]
@xfrnk2 

1. 파이썬 모듈로 선언하는 부분은 다 __init__.py 파일이 필요합니다.
즉 tests 에 넣어서 해결이 아니라 (모듈로 외부에 노출할 모든) 소스 폴더에 모두 추가해야 하죠.

2. https://citynetc.tistory.com/72
이 링크를 유심히 읽어보세요.

문자열에는 인덱스 기반 대입 기능이 없습니다.
대신 replace가 있죠.
아니면 문자열을 문자 list로 바꾸고 나중에 ‘’.join(list)로 합치는 방법도 있겠네요.

**Comment by xfrnk2** [comment]
@zrma 감사합니다. 아직 계속 해보고 있어요.

**Comment by xfrnk2** [comment]
@zrma 
문제를 잘못 읽었었네요.. 이게 왜 안풀리지 고민 많이 했는데. 여태까지 잘못 풀고 있었어요.
그래서 새롭게 구성해서 코딩을 하는데 좀 어려운부분이 하나 생겼는데요..

문자열을 문자 list로 바꾸고 나중에 ''.join(list)로 합치려는 순서인데 뭐가 문제일까요?

r은 list고 x는 원소가 상수인 list에요.
    for x in r:
        x = [str(value) for value in x] <- 상수를 문자열로 바꿈
        x = ''.join(x) <- 이 부분에서 TypeError: sequence item 0: expected str instance, int found 에러가 나타나요.  윗줄에서 해결한 것 같은데 잘 모르겠어요.
    return r

**Comment by zrma** [comment]
@xfrnk2 

> for x in r:
x = [str(value) for value in x]
x = ''.join(x)
return r

띄어쓰기가 엉망이라 코드 문맥을 못 읽겠습니다.

**Comment by xfrnk2** [comment]
@zrma 
앗 죄송해요.. 수정했어요.
for x in r:
      x = [str(value) for value in x]
      x = ''.join(x)

**Comment by zrma** [comment]
@xfrnk2 
우선 x는 for loop 내부에서 할당한 지역변수인데 이걸 덮는다고 r 안에 저장 될까요?

그리고 `x = ‘’.join(map(str, x))` 
이렇게 쓰면 될 것 같네요.

**Comment by xfrnk2** [comment]
@zrma 해결되었어요! 감사합니다

**Comment by zrma** [comment]
@xfrnk2 이 이슈는 닫습니다.
