### ISSUE TITLE
Use itertools.product

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#214]
https://github.com/xfrnk2/1d1c/blob/851489d74b3abe783c9f6031e61f6d7b266d4c30/src/hackerrank/Problem_Solving/Cavity_Map.py#L12

```python
for i, j in itertools.product(range(1, length - 1), range(1, length - 1)):
```

**Comment by xfrnk2** [comment]
@zrma 감사합니다!

**Comment by zrma** [comment]
@xfrnk2 확인.
