### ISSUE TITLE
remove duplicated code, eager return, varaibles name convention.

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#218]
https://github.com/xfrnk2/1d1c/blob/0b9fce41cde2c6d49a3f950484665807025fc702/src/hackerrank/Problem_Solving/Fair_Rations.py#L6

코드 조건식 중첩이 뭔가 이상하고 복잡하고 그러네요.

그리고 파이썬 컨벤션(pep8)에 따르면 변수명을 대문자로 하면 안 됩니다.

```python
    if arr[0] % 2 == 1:
        return "NO"

    for x in range(length - 1, 0, -1):
        if arr[x] % 2 == 1:
            arr[x], arr[x - 1] = arr[x] + 1, arr[x - 1] + 1
            count += 2

    return count
```

**Comment by xfrnk2** [comment]
@zrma 감사합니다! 수정했어요.

**Comment by zrma** [comment]
@xfrnk2 확인했어요
