### ISSUE TITLE
Delete .idea folder and ignore it.

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#228]
@xfrnk2 

1. delete .idea folder
2. commit and push
3. visit https://gitignore.io
4. query with keywords: Python, JetBrains+all, Windows, and other things if you need them.
5. add .gitignore file an result of step 4 to repository, commit and push.

**Comment by xfrnk2** [comment]
@zrma 끝냈습니다!

**Comment by zrma** [comment]
@xfrnk2 

GJ
