### ISSUE TITLE
This result has an error.

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#242]
https://github.com/xfrnk2/1d1c/blob/fb5f9a27a54a9327db490898baaa1bbfafccd999/Question/for_Loop_Efficiency.py#L34

@xfrnk2 

I've run this example several times and the result is:

```
5.802886724472046 7.879844903945923
13.933361768722534 8.841026067733765
9.254027366638184 10.01003098487854
9.72893214225769 8.547868013381958
9.36400556564331 9.712544202804565
10.765186786651611 8.761521816253662
9.343003034591675 9.398005723953247
9.491997241973877 8.26103162765503
9.324023962020874 9.78601622581482
9.64597773551941 8.317001104354858
```

It took more time since the first run.
This is because from the second time the garbage collector was running.

**Comment by zrma** [comment]
@xfrnk2 

I checked it.

**Comment by xfrnk2** [comment]
@zrma 

현재로선 fb5f9a2 커밋의 코드에서 for루프로 10번 정도 테스트 해본 결과, 걸린 시간이랑 회차별 걸린 시간이 크게 차이가 나지 않는데, 이후에 수정한 코드에서도 걸리는 시간이 별로 차이가 나지 않았어요. 에러가 나는 부분이 어디이고 어떻게 바꾸면 좋을까요?

**Comment by zrma** [comment]
@xfrnk2 

주석에 남겨둔 실험 결과가 오차범위 내라서 유의미하지 않다는 의미였어요.

성능 상 확연히 큰 차이가 없다면 가독성 좋은 코드를 작성하는 것이 좋을 것 같습니다.

그리고 실험은 변인통제를 하고 테스트하는 것이 좋을 것 같아요.

**Comment by xfrnk2** [comment]
@zrma 덕분에 가비지 컬렉션에대해 알아보게되었네요 감사합니다
