### ISSUE TITLE
numpy is not good to practice algorithm

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#251]
https://github.com/xfrnk2/1d1c/blob/ac7f55fc2f85f2205c25c0751d5d8f20103e93df/baekjoon/Coin0.py#L61

baekjoon programming practice make you do more thinking, 
and it'll help you to be better programmer with optimized algorithm.

numpy is c language implements, so it's not good to improve your algorithm ability.
do not use numpy.

for example, use O(nlogn) instead of O(n^2)

**Comment by xfrnk2** [comment]
@zrma 리뷰 감사합니다! 재귀함수 형태로 바꾸고 numpy 대신 itertools.chain을 사용하도록 수정했어요

**Comment by zrma** [comment]
@xfrnk2 lgtm
