### ISSUE TITLE
what will be happened if it’s not hitting this condition?

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#256]
https://github.com/xfrnk2/1d1c/blob/9549aa0ac66f7ca71bd380332e14b2f0548ab741/baekjoon/Plus_Cycle.py#L10

@xfrnk2 

what will be happened?

**Comment by xfrnk2** [comment]
@zrma value와 number의 값을 비교해서 두 값이 같아지면 while문이 끝나게 됩니다
 혹시 제가 여기서 그냥 넘어가서는 안되는 부분이 있을까요?

**Comment by zrma** [comment]
@xfrnk2 두 값이 안 같아지면요?

**Comment by xfrnk2** [comment]
@zrma while 루프를 쓰는게 적절치 못했던 것 같아요. 리턴값이 있는 재귀함수로 수정했습니다!

**Comment by zrma** [comment]
@xfrnk2 

예전 코드에서 `while` 루프 사용 할 때 number 값에 12345 로 넣으면 무한루프에 빠졌어요.

그리고 지금 재귀 버전에서는 12345를 넣으면 재귀 깊이 초과로 터지죠.

> RecursionError: maximum recursion depth exceeded in comparison

**Comment by xfrnk2** [comment]
@zrma 으음 코드를 조금 바꿔봤는데 100이상 넘어가면 항상 터지네요....
반환하는 숫자를 12345의 경우 5 + 5 = 50으로 했는데 어느순간 0으로 수렴하는 것 같은데..

혹시 더하기 사이클이라는 것이 0~99까지의 숫자에만 적용되는것이 아닐까요?
최종 값이 초기값과 같아지게 하는 방법을 못 찾겠... 반환값은 항상 두자리 수 이어서요
#266

**Comment by xfrnk2** [comment]
assertion 코드를 추가하는게 적절한 방법 같아요

**Comment by zrma** [comment]
@xfrnk2 

우선 `while` 구문을 사용할 때는 당연히 무한루프를 조심해야 합니다.
또한 재귀 함수도 잘 쓰면 유용하지만, 잘못 사용하면 지금처럼 호출 스택 과다로 터지죠.

그래서 재귀 함수를 다시 꼬리 재귀 형태로, 그리고 루프 형태로 변형할 줄 알아야 합니다.
또한 그 루프에서 무한루프에 빠지지 않도록 안전한 형태의 종료 조건을 설정해야 하구요.

더 고민해 보세요.

**Comment by xfrnk2** [comment]
@zrma 감사합니다 중요한걸 알게되었네요 알려주신것 배경삼아 코드 수정했습니다

**Comment by zrma** [comment]
@xfrnk2 

재귀에 대해서 앞으로도 계속 공부 해 보세요.
나중에 함수형 프로그래밍 패러다임에 대해 살펴볼 기회가 있다면 함께 봐도 좋습니다.

- 꼬리 재귀 최적화
- 트램폴린 재귀
- 메모이제이션

**Comment by zrma** [comment]
@xfrnk2 이 이슈는 닫습니다.
