### ISSUE TITLE
재귀는 루프로 바꿀 수 있습니다.

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#268]
https://github.com/xfrnk2/1d1c/blob/c51aa9aa513240a19c63fe7a86e6c8ab4e05a6b0/baekjoon/Number_Sum.py#L2

@xfrnk2 

https://namu.wiki/w/%EC%9E%AC%EA%B7%80%ED%95%A8%EC%88%98

정독해 보세요.

그리고 재귀가 매우 유용한 곳들이 여럿 있지만,
작지 않은 단위의 값이나 데이터를 다룰 때에는 대부분 터질 겁니다.

특수한 런타임(꼬리 재귀 최적화를 지원하는 함수형 언어 계열)이 아니고서는...

어지간하면 그래서 재귀는 함수 호출 스택이 터지지 않는 규모 내에서만 사용하거나
루프 형태로 바꿔서 사용하죠.

**Comment by xfrnk2** [comment]
@zrma 네 감사합니다!
