### ISSUE TITLE
use local variables with explicit name

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#281]
https://github.com/xfrnk2/1d1c/blob/c2cba3a84e99ee2d12e1124057c025580a04736a/Algorithm/sort_heap_sort.py#L4

@xfrnk2 

what means `index * 2`, `index * 2 -1`, `index * 2 - 2`, `i`?

I think it’s more explicit to use like `left_child_idx`, `right_child_idx`, `current_idx`.
It’s more clear than `index * 2 - 2`, etc `i`, isn’t it?

**Comment by xfrnk2** [comment]
@zrma 감사합니다!

**Comment by zrma** [comment]
@xfrnk2 LGTM
