### ISSUE TITLE
정렬 하지 않고 풀기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#3]
https://github.com/xfrnk2/1d1c/blob/94a67fd33a787c273b2c3aff59e3ac3a0a1b5b7a/hackerrank/Problem_Solving/Mini-Max_Sum.py#L11

이 문제는 정렬을 하지 않고 단 한 번의 순회만으로 풀 수 있습니다.

정렬을 하면 시간 복잡도가 O(n*logn) 또는 O(n^2 )으로 늘어납니다.
게다가 리스트의 index 0 이나 len-1에 임의 접근하는 것도 비효율적이고요.

**Comment by xfrnk2** [comment]
감사합니다. for문으로 한번에 순회하면서 max()와 min()으로 해결하려고 했더니, 테스트 케이스중에 모든 값이 같은 경우(5, 5, 5, 5)에는 오류가 나는것을 보고 아래와 같이 바꿨어요. 
    v = sum(arr)
    print(v - max(arr), v - min(arr))

**Comment by xfrnk2** [comment]
일.. 뻔 했는데, 다른 코멘트 중에서 max()와 min()이 전체를 한번 순회하게 된다는 말씀을 듣고 for문 한번으로 마칠수 있게 수정했어요.
    min = max = arr[0]

    for n in arr:
        if max < n:
            max = n
        if min > n:
            min = n

    all = sum(arr)
    min, max = all - max, all - min
    print(min, max)

**Comment by zrma** [comment]
풀이에서 `all = sum(arr)` 이걸 아래에서 할 필요가 있나요.
위쪽 한 번 순회 할 시점에 min, max 체크하면서 덤으로 `all += n` 으로 구해도 될 것 같습니다.

그리고 `min`, `max` 같은 이름은 파이썬 built-in function name과 동일해서 shadowing이 발생합니다.
shadowing에 대해서 학습해 보시고, 적절한 다른 이름으로 변경하는 것이 좋을 것 같아요.

**Comment by xfrnk2** [comment]
넵 감사합니다 반영했어요.

**Comment by zrma** [comment]
@xfrnk2 

https://github.com/xfrnk2/1d1c/blob/db4de95ebc891951080cfd513a85b55d04377518/hackerrank/Problem_Solving/Mini-Max_Sum.py#L13

만약 리스트 `arr`의 사이즈가 0이라면?

**Comment by xfrnk2** [comment]
감사합니다 함수 제일 첫부분에 아래와 같이 추가해 넣었어요

    if len(arr) < 5:
        print("Wrong input")
        exit()

**Comment by zrma** [comment]
@xfrnk2 Good!
