### ISSUE TITLE
커밋 코멘트 정확히 달기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#33]
@xfrnk2

5b5bae9c1bb39579af2cf6e3ce168aff04176658 
해당 커밋의 코멘트는 해당 커밋 내용과는 다른 내용인 것 같습니다.
적절한 코멘트로 수정해 봅시다.

`git rebase` 명령어를 통해서 과거의 커밋 코멘트를 수정(`reword`) 가능합니다.
소스트리 등의 툴에서 interactive rebase 도 가능합니다.

학습해 봅시다.

**Comment by xfrnk2** [comment]
감사합니다 수정했어요. 혹시 중간의 커밋 히스토리만 삭제할수는 없을까요?

**Comment by zrma** [comment]
@xfrnk2 squash 명령으로 커밋 합치기가 가능합니다.
