### ISSUE TITLE
조건문 제거하기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#34]
@xfrnk2 

https://github.com/xfrnk2/1d1c/blob/3f982f49a3661fa94f026286e5c07eacf9fcb725/hackerrank/Problem_Solving/Breaking_The_Records.py#L19

13번째 줄에서 초기화하는 hv가 `-sys.maxsize`, lv가 `sys.maxsize` 값이라면
19번째 줄의 조건문을 매 루프마다 반복하지 않아도 되지 않을까요?

**Comment by xfrnk2** [comment]
감사합니다!

**Comment by zrma** [comment]
@xfrnk2 확인 했습니다.
