### ISSUE TITLE
테스트 코드 폴더에 적절한 명칭 붙이기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#35]
@xfrnk2 
`tdd`라는 폴더명보다는 `tests` 정도가 적당할 것 같네요

https://github.com/zrma/tdd 이 저장소를 보고 참고하여

1) travis-ci 에서 빌드 자동화를 해 보고 그 결과를 README.md에 badge로 등록합니다.
2) travis-ci 확장 기능(sonar-scanner)으로 sonar-cloud 서버에 report 하고 그 quality gate 결과를 얻어 badge에 추가합니다.
3) coveralls.io 에서 소스코드 커버리지를 집계 해 보고 badge에 추가합니다.

**Comment by xfrnk2** [comment]
지난번에 이것 구현하려고 며칠간 애를 좀 썼는데 (travi-ci는 됬지만 그외에는 사실 잘 안되서 전에 만들어주신 tdd 레파지토리 따서 그냥 복붙을 했어요) 좀 어려웠어요. 요즘은 손을 잘 못대고 있지만 꼭 해보도록 할게요. 어려움 있으면 좀 여쭤볼게요.

**Comment by zrma** [comment]
@xfrnk2 
개념적 이해가 필요한 부분이 여럿 있을거에요.

lint, test + coverage, sonarqube, coveralls.
travis-cli secure token. 등등...

차근차근, 하지만 정확하게 원리를 파악하면서 확인해 보세요.
