### ISSUE TITLE
코드 논리성 문제

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#37]
**https://github.com/xfrnk2/1d1c/blob/3f982f49a3661fa94f026286e5c07eacf9fcb725/hackerrank/Problem_Solving/Migratory_Birds.py#L29**

@xfrnk2 
```python
for num, val in box.items():
        if val > temp:
            # 여기서 temp = val 으로 대입을 했으니
            temp = val
            temp_num = num
        # 만약 26번째 줄(val > temp)이 참이라면 여기도 무조건 참입니다.
        if val == temp:
            # 그러면 아래의 if num < temp_num 은 거짓이므로 아래의 연산은 무효합니다.
            if num < temp_num:
                temp_num = num
                temp = val
```

위에서 설명한 것처럼 해당 줄은 `elif val == temp` 를 붙이거나
위의 `temp_num = num` 아랫 줄에서 `continue` 를 추가하면 될 것 같습니다.

**Comment by xfrnk2** [comment]
넵 감사합니다

**Comment by zrma** [comment]
@xfrnk2 확인했습니다.
`for loop` 내부를 별도 함수로 분리해도 괜찮을 것 같네요.
