### ISSUE TITLE
변수 할당, 가독성 문제

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#4]
https://github.com/xfrnk2/1d1c/blob/94a67fd33a787c273b2c3aff59e3ac3a0a1b5b7a/hackerrank/Warm_Up/Repeated%20String.py#L14

len(s)를 두 번 수행하지 말고 변수에 할당 한 후에 그 변수를 2번 사용하는 게 어떨까요?
‘a’를 코드 내에 하드코딩 하지 말고, findTarget = ‘a’ 같은 형태로 문자 리터럴 상수나 변수로 저장해서 사용하는 건 어떨까요?

**Comment by xfrnk2** [comment]
감사합니다 반영했어요

**Comment by zrma** [comment]
@xfrnk2 반영한 코드를 아직 push 하지 않았나 보네요?
저장소에서 보이지 않습니다.

**Comment by xfrnk2** [comment]
네 한번에 하려던 생각에 잠시 미뤄두고 있었네요.. 먼저 지금까지 된 것 까지 업로드 했어요.

**Comment by xfrnk2** [comment]
지금까지 코드리뷰 해주신것은 전부 반영해서 올렸습니다

**Comment by zrma** [comment]
@xfrnk2 Good!
