### ISSUE TITLE
충돌 해결

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#5]
https://github.com/xfrnk2/1d1c/blob/94a67fd33a787c273b2c3aff59e3ac3a0a1b5b7a/hackerrank/Warm_Up/Sock%20Merchant.py#L91

conflict 정도는 해결하고 올립시다.

**Comment by xfrnk2** [comment]
감사합니다

**Comment by zrma** [comment]
@xfrnk2 Good!
