### ISSUE TITLE
불필요한 elif 제거

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#51]
https://github.com/xfrnk2/1d1c/blob/c315d90442fc33b0c9276d0421a1ac6769a94238/hackerrank/Problem_Solving/Divisible_Sum_Pairs.py#L19

@xfrnk2 위에서 `return 0` 했는데 여기서 `elif`가 필요한가요?

**Comment by xfrnk2** [comment]
if로 수정했어요

**Comment by zrma** [comment]
@xfrnk2 확인했어요~
