### ISSUE TITLE
불필요한 elif 2

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#52]
https://github.com/xfrnk2/1d1c/blob/c315d90442fc33b0c9276d0421a1ac6769a94238/hackerrank/Problem_Solving/Divisible_Sum_Pairs.py#L23

@xfrnk2 여기도 마찬가지 불필요한 `elif`

**Comment by xfrnk2** [comment]
네 감사합니다 여기도 if로 바꿨어요..

**Comment by zrma** [comment]
@xfrnk2 확인했습니다!
