### ISSUE TITLE
뎁스 줄이기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#53]
https://github.com/xfrnk2/1d1c/blob/c315d90442fc33b0c9276d0421a1ac6769a94238/hackerrank/Problem_Solving/Divisible_Sum_Pairs.py#L24

@xfrnk2 위의 if 구문과 합쳐서 한 줄로 작성 가능할 것 같네요.

**Comment by xfrnk2** [comment]
넵 감사합니다

**Comment by zrma** [comment]
@xfrnk2 Good!
