### ISSUE TITLE
불필요한 enumerate 제거

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#54]
https://github.com/xfrnk2/1d1c/blob/c315d90442fc33b0c9276d0421a1ac6769a94238/hackerrank/Problem_Solving/Breaking_The_Records.py#L19

@xfrnk2 
`if i == 0:` 구문이 사라져서 인덱스 값이 더 이상 필요하지 않네요.

**Comment by xfrnk2** [comment]
감사합니다

**Comment by zrma** [comment]
@xfrnk2 보편적으로 index는 i를 많이 사용합니다.

**Comment by zrma** [comment]
@xfrnk2 Good!
