### ISSUE TITLE
구문 축약 가능

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#57]
https://github.com/xfrnk2/1d1c/blob/d300ad6dfbcb534a036a7a8963c811f862d2f3a3/hackerrank/Problem_Solving/Divisible_Sum_Pairs.py#L21

`return len(list(permutations(ar, 2)))` 

정도로 줄일 수 있을 것 같네요.

**Comment by zrma** [comment]
https://stackoverflow.com/questions/3345785/getting-number-of-elements-in-an-iterator-in-python

덤으로 이 글을 읽어보면 좋을 것 같습니다 :)

**Comment by xfrnk2** [comment]
넵 감사합니다

**Comment by zrma** [comment]
@xfrnk2 확인했습니다!
