### ISSUE TITLE
시간복잡도 문제

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#6]
https://github.com/xfrnk2/1d1c/blob/94a67fd33a787c273b2c3aff59e3ac3a0a1b5b7a/hackerrank/Warm_Up/Sock%20Merchant.py#L74

이렇게 풀면 X를 순회하며 매 루프마다 ar.count(x)를 통해 내부에서 또 루프를 돌게 됩니다.
파이썬 list의 count 함수는 모든 원소를 다 훑어서 확인해야 하므로 비효율적입니다.

예를 들어 중복 되지 않은 원소 100만개가 들어 있는 리스트를 이런 알고리즘으로 풀면
100만 루프(바깥 for-loop:X) * 100만 루프(안쪽 for-loop:count) = ?

이렇게 풀면 망하는거죠.

100만 루프 * 100만 루프의 형태가 아니라, 100만 루프 + 100만 루프 형태로 풀어야 합니다.
dictionary를 사용하세요.

**Comment by xfrnk2** [comment]
그러네요 감사합니다 반영했어요

**Comment by zrma** [comment]
@xfrnk2 Good!
