### ISSUE TITLE
정수 나누기를 사용합시다

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#60]
https://github.com/xfrnk2/1d1c/blob/e82da773717ebf3be0abe61f73227939f13d115c/hackerrank/Problem_Solving/Bon_App%C3%A9tit.py#L19

@xfrnk2 
```python
v = v // 2
```

**Comment by xfrnk2** [comment]
감사합니다

**Comment by zrma** [comment]
@xfrnk2 integer -> float -> integer 형변환은 모두 비용이거든요 :)
