### ISSUE TITLE
elif -> if

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#61]
https://github.com/xfrnk2/1d1c/blob/e82da773717ebf3be0abe61f73227939f13d115c/hackerrank/Problem_Solving/Cats_And_A_Mouse.py#L20

@xfrnk2 
위에서 `return` 했는데 `elif`가 필요할까요?

**Comment by xfrnk2** [comment]
감사합니다 수정했어요.

    if c1 == c2:
        return("Mouse C")
    if c1 > c2:
        return("Cat A")    
    return("Cat B")

**Comment by zrma** [comment]
@xfrnk2 Good!
