### ISSUE TITLE
선언하지 않은 변수의 사용

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#66]
https://github.com/xfrnk2/1d1c/blob/6a5d23314c760eaa87aadc9055b4813661f1c1f7/hackerrank/Problem_Solving/Birthday_Chocolate.py#L14

@xfrnk2 `n`은 어디에서 나온 변수인가요?

**Comment by xfrnk2** [comment]
main 영역에 포함되고 변수s의 크기(길이)를 나타내는 변수인데 그냥 가져다가 썼네요.. 함수 안에 n = len(s) 추가했어요.

**Comment by zrma** [comment]
@xfrnk2 Good!
