### ISSUE TITLE
컨벤션 문제

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#7]
https://github.com/xfrnk2/1d1c/blob/94a67fd33a787c273b2c3aff59e3ac3a0a1b5b7a/hackerrank/Warm_Up/Sock%20Merchant.py#L71

파이썬에서 지역변수는 대문자로 표기하지 않습니다(pep8)

**Comment by xfrnk2** [comment]
넵 감사합니다..

**Comment by zrma** [comment]
@xfrnk2 Good!
