### ISSUE TITLE
itertools 사용하기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#71]
https://github.com/xfrnk2/1d1c/blob/6cc16a4b4671e5d1ba5031210498c3d2de987599/hackerrank/Problem_Solving/Electronics_Shop.py#L14

@xfrnk2 

```python
for x in keyboards:
    for y in drives:
````

이 두 줄은

```python
for x, y in itertools.product(keyboards, drives):
```

한 줄로 줄일 수 있겠네요.
itertools 내의 함수는 lazy evaluate  되는 generate를 반환합니다.

리스트와 iteratable generater의 차이는 무엇일까요?

**Comment by xfrnk2** [comment]
넵 감사합니다

**Comment by xfrnk2** [comment]
리스트는 호출되었을때 모든 원소들을 메모리에 적재하는데 비해 제너레이터는 next()메소드로 차례로 값에 접근할때마다 적재하는 방식이라 둘의 차이는 동작방식이 다른것과 메모리 효율인걸로 이해 했어요.
다르게 말하면 제너레이터는 원하는 결과값이 필요할때까지 계산을 늦추는 효과가 있고,  리스트의 규모가 클수록 제너레이터의 효율성이 더 좋아지는 것 같아요.

**Comment by zrma** [comment]
@xfrnk2 확인했어요 :)
