### ISSUE TITLE
코드 정리

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#72]
https://github.com/xfrnk2/1d1c/blob/6cc16a4b4671e5d1ba5031210498c3d2de987599/hackerrank/Problem_Solving/Electronics_Shop.py#L20

@xfrnk2 

`x`와 `y`의 범위가 0보다 크거나 같다면 두 수의 합인 `z`는 음수가 나올 수 없겠죠?

그러면 이렇게 `if` 구문으로 비교할 것 없이 
처음부터 12번째 줄에서 `values` 리스트를 초기화 하는 시점에 

`values = [-1]` 로 초기화 하면 어떨까요?
그러면 이처럼 `if`로 비교할 것 없이 바로 `return max(values)` 하면 될 것 같아요.

**Comment by xfrnk2** [comment]
우와..명쾌하네요 감사합니다 반영했어요

**Comment by zrma** [comment]
@xfrnk2 Good!
