### ISSUE TITLE
built-in 함수 filter 사용하기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#73]
https://github.com/xfrnk2/1d1c/blob/6cc16a4b4671e5d1ba5031210498c3d2de987599/hackerrank/Problem_Solving/Picking_Numbers.py#L28

@xfrnk2 

```python
for _ in filter(lambda x: x == num or x == num - 1):
    count += 1
```

이렇게 쓸 수도 있겠네요.

**Comment by xfrnk2** [comment]
넵 감사합니다

**Comment by zrma** [comment]
@xfrnk2 Good!
