### ISSUE TITLE
set 자료구조는 정렬 된 순서 아닌가요?

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#74]
https://github.com/xfrnk2/1d1c/blob/6cc16a4b4671e5d1ba5031210498c3d2de987599/hackerrank/Problem_Solving/Picking_Numbers.py#L21

@xfrnk2 
그 앞에서 리스트 `sort()` 없이 바로 `set()`으로 변환하는 건 어때요?

**Comment by xfrnk2** [comment]
필요없는 문장이었네요.. 알려주셔서 감사합니다

**Comment by zrma** [comment]
@xfrnk2 확인했어요~
