### ISSUE TITLE
코드 정리

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#78]
https://github.com/xfrnk2/1d1c/blob/399fa070a7c76be152438af7bcc056201cb23e35/hackerrank/Problem_Solving/Electronics_Shop.py#L16

@xfrnk2 
#72 에서 언급한 것처럼 `z >= 0` 인 사실은 자명하니까

`if mx < z <= b:`

이렇게 간결하게 줄일 수 있겠네요.

**Comment by xfrnk2** [comment]
감사합니다

**Comment by zrma** [comment]
@xfrnk2 Good!
