### ISSUE TITLE
변수명 가독성

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#79]
https://github.com/xfrnk2/1d1c/blob/399fa070a7c76be152438af7bcc056201cb23e35/hackerrank/Problem_Solving/Electronics_Shop.py#L13

@xfrnk2  

`mx`는 `max`의 줄임말이지만 built-in 함수랑 겹치기 때문에 이렇게 축약해서 썼겠죠?
그냥 `max_value` 라고 하면 어때요?

`mx`라고 하면 왠지 `m`(ax)`z`를 의미하는 것 같이 느껴져서 
`mx`와 `z`를 비교하는게 이상해 보이네요.

**Comment by xfrnk2** [comment]
넵 감사합니다 앞으로 최댓값은 max_value처럼 누가 봐도 알수있는 이름으로 써야겠어요

**Comment by zrma** [comment]
@xfrnk2 Good!
