### ISSUE TITLE
루프 횟수 줄이기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#8]
https://github.com/xfrnk2/1d1c/blob/94a67fd33a787c273b2c3aff59e3ac3a0a1b5b7a/hackerrank/Problem_Solving/Birthday_cake_candles.py#L11

이렇게 풀면 max() 함수에서 전체를 순회해서 최대 값을 뽑을테니 루프 한 번
count() 함수에서 전체를 또 순회해서 수를 셀테니 루프 또 한 번 도네요.

단 한 번의 루프만으로 문제를 해결할 수 있습니다.

**Comment by xfrnk2** [comment]
감사합니다.. 아래처럼 풀었어요.

    max = ar[0]
    candles = {max : 0}

    for x in ar:
    
        if  max < x:
            max = x
            candles[max] = 1
        elif max == x:
            candles[max] += 1

    return candles[max]

**Comment by zrma** [comment]
@xfrnk2 

`max`가 built-in function을 가립니다(`shadow`)

`candles` 자료구조로 꼭 dictionary를 사용해야 할까요?
정수값 변수 하나만 있으면 될 것 같습니다.

**Comment by xfrnk2** [comment]
넵 감사합니다

**Comment by zrma** [comment]
@xfrnk2 Good!
