### ISSUE TITLE
변수명 가독성

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#80]
https://github.com/xfrnk2/1d1c/blob/399fa070a7c76be152438af7bcc056201cb23e35/hackerrank/Problem_Solving/The_Hurdle_Race.py#L12

@xfrnk2 
변수명을 무작정 줄이기보다는, 어떻게 하면 눈에 더 잘 들어올지 더 고민해 보는 게 어떨까요?

`mx`에서 최대값이라는 의미를 알 수 있을까요?
그렇다면 최소값은 `mn`으로 써야 할까요?

이런 경우는 차라리 `max_val` 이나 `max_value` 같이 풀어서 명시적으로 서술하는게 어때요?

**Comment by xfrnk2** [comment]
그러네요.. 좋은 말씀 감사합니다~

**Comment by zrma** [comment]
@xfrnk2 Good!
