### ISSUE TITLE
테스트 코드 추가하기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#82]
@xfrnk2 

해커랭크 문제 풀이 할 때 문제에서 나오는 테스트 케이스를  
`tests` 폴더 안에 같은 폴더 구조로 추가해서 테스트 하면 되지 않을까요?

아무래도 지금 살짝 코딩하고 해커랭크에서 돌려보고, 
또 코딩하고 돌려보고 이런 식으로 진행할 것 같은데...

그런 식으로 매번 웹 페이지에 붙여넣고 실행 하는 식으로 진행하지 말고
`tests` 폴더를 놀려두지 말고 pycharm에서 pytest를 이용해서 자동화 테스트를 진행하면 좋지 않을까요?

**Comment by xfrnk2** [comment]
넵 감사합니다

**Comment by xfrnk2** [comment]
앞으로 항상 문제를 풀때마다 말씀해주신 형태로 진행할게요

**Comment by zrma** [comment]
@xfrnk2 Good!
