### ISSUE TITLE
casting 하지 않고 풀기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#85]
https://github.com/xfrnk2/1d1c/blob/c9d778950b0284bf732138d65aa8a790f3f327a5/hackerrank/Problem_Solving/Find_Digits.py#L8

@xfrnk2 

문자열로 캐스팅하고 다시 그걸 정수형으로 캐스팅 하는 형태로 풀지 않아도 될 것 같아요.

가령 1234라고 하면
1의 자리 수 : `1234%10`
10의 자리 수 : `(1234%100)/10`
100의 자리 수 : `(1234%1000)/100`
1000의 자리 수 : `(1234%10000)/1000`

곰곰이 생각해보면 각 자리 수를 뽑아내는 건 간단하죠.

**Comment by xfrnk2** [comment]
넵 감사합니다

아래와 같이 수정했어요.

def findDigits(n: int) -> int:
    if n == 1:
        return n

    l = len(str(n))
    count = 0

    for x in range(1, l + 1):
        num = int((n % 10 ** x) / 10 ** (x - 1))
        if num == 0:
            continue
        if n % num == 0:
            count += 1

    return count

**Comment by zrma** [comment]
@xfrnk2 수정한 코드 커밋을 안 하셨네요

**Comment by xfrnk2** [comment]
@zrma 죄송해요 빠르게 푸쉬하겠습니다

**Comment by zrma** [comment]
@xfrnk2 good!
