### ISSUE TITLE
리스트로 저장 안 하기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#86]
https://github.com/xfrnk2/1d1c/blob/c9d778950b0284bf732138d65aa8a790f3f327a5/hackerrank/Problem_Solving/Minimum_Distances.py#L13

@xfrnk2 
이전 원소의 distance하고 index만 있으면 되지 않나요?
새로 들어온 원소의 index와 거리 비교해서 더 짧으면 거리와 index를 갱신, 아니면 패스

굳이 저 모든 원소의 인덱스를 dict 내의 list 형태로 중첩해서 갖고 있으려다보니
자료구조의 깊이가 깊어지고 가독성도 떨어지네요.

`minDist`로 최단거리 값 하나만 갱신 하는 형태로 하면
지금처럼 몇 중첩의 for loop를 여러번 돌 필요가 없어보이네요.
딱 한 번 for-loop 돌면 끝날 것 같아요.

**Comment by xfrnk2** [comment]
앗 그런방법이.. 감사합니다.
아래처럼 수정했어요.

    length = len(a)
    minDist = -1
    if length == 1:
        return minDist
    for x in range(length):
        for y in range(x + 1, length):
            if a[x] == a[y]:
                if minDist == -1:
                    minDist = y - x
                else:
                    if y - x < minDist:
                        minDist = y - x
    return minDist

**Comment by zrma** [comment]
@xfrnk2 아뇨.
루프를 2중으로 돌지 않고 한 번만 도는게 핵심이라니까요.

시간복잡도가 O(n^2)과 O(n)은 엄청난 차이입니다.

**Comment by xfrnk2** [comment]
@zrma 
감사합니다. 고민 많이 했네요..
아래와같이 수정했습니다

   minDist = sys.maxsize
    index_box = {}
    for i, j in enumerate(a):
        if j in index_box:
            minDist = min(minDist, i - index_box[j])
        index_box[j] = i
    return minDist if minDist != sys.maxsize else -1

**Comment by zrma** [comment]
@xfrnk2 

Good! 코드가 많이 깔끔해졌네요.
고민 많이 해야 해요.
