### ISSUE TITLE
불필요한 리스트 생성하지 않기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#9]
https://github.com/xfrnk2/1d1c/blob/94a67fd33a787c273b2c3aff59e3ac3a0a1b5b7a/hackerrank/Problem_Solving/Diagonal_Difference.py#L11

인덱스를 리스트 형태로 생성하지 말고, 현재 인덱스를 가리키는 변수 2개를 생성한 후에
그 인덱스만 증감 형태로 사용하면 될 것 같습니다.

배열을 만드는 순간 그 배열 크기만큼 메모리를 사용합니다.

**Comment by xfrnk2** [comment]
감사합니다. 반영시켰어요~

**Comment by zrma** [comment]
@xfrnk2 Good!
