### ISSUE TITLE
순회 한 번으로 해결하기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#90]
https://github.com/xfrnk2/1d1c/blob/072c03d0f3dd96ad43221c893743a1433547e234/hackerrank/Problem_Solving/CutTheSticks.py#L13

@xfrnk2 

`sorted(arr)`의 배열을 앞에서부터 순서대로 `pop()` 하면서 이전 원소와 값이 같은지 확인하면서  
같은 값의 개수를 센 후 값이 달라질 때마다 그 개수만큼 빼는 방식으로 하면

위에서의 불필요한 `set()` 변환도 필요 없고  
아래에서의 불필요한 순회나 `list()` 캐스팅이나 `filter()` 함수도 필요 없을 것 같아요.

바로 한 번의 순회만으로 간단하게 계산 가능할 것 같습니다.

**Comment by xfrnk2** [comment]
순서대로 pop() 한다는 말씀이 약간 아리송한데 순회중에 pop()을 하면 에러가 나는게 보통이라 다른 방법이 없을지 궁리 하고 있었네요..  현재로는 만든 코드가 아래와 같은데 순서대로 pop()하는 것에 부연설명을 부탁드려도 될까요?

    arr = sorted(arr)
    length = len(arr)
    answer = [length]
    front_num = 0
    while 1 < length:
        n = arr.pop(0)
        if n == front_num:
            continue
        count = 1
        for x in arr:
            if n == x:
                count += 1
        length -= count
        answer.append(length)
        front_num = n
    return answer

**Comment by xfrnk2** [comment]
커밋만 하고 푸쉬를 안하고(한꺼번에 하려고...) 있어서 번거롭게 해드렸네요. 금방 될거같은데 해서 그만 이 문제에서 시간을 쓰는 바람에..

**Comment by zrma** [comment]
@xfrnk2  pop 할 list 따로, 순회할 list 따로 쓰는거죠.

**Comment by zrma** [comment]
@xfrnk2 우선 문제를 풀이한 알고리즘 자체가 맞았는지 틀렸는지는 모르겠고요.

원칙적으로 풀자면
매 루프 때마다 sorted 해서 가장 짧은(가장 앞쪽의) 원소 값만큼 전체 값을 감소 시키고
0인 원소는 모두 제거하고 남은 원소가 없을 때까지 반복해서 풀어야 올바른 답이 나올 것 같은데...
(그래서 풀어놓은 로직이 조금 이상하게 느껴졌어요. 몇몇 특수 케이스만 푼 것 같아서...)

아무튼 위의 이야기는 차지하고서라도, 기존에 풀어놓았던 알고리즘의 경우더라도
루프 한 번만으로 같은 역할을 할 것 같아서 이야기한 거였어요~

**Comment by xfrnk2** [comment]
@zrma 감사합니다. 말씀해주신 덕분에 해결하는데 많은 도움이 됬어요
아래와 같이 수정했습니다
    a2 = sorted(arr)
    size = len(a2)
    ans = [size]
    target = -1
    numCount = 1
    for x in a2:
        if target == -1 :
            target = x
            continue  
        if target == x:
            numCount += 1           
        else:
            size -= numCount
            if size == 1:
                ans.append(1)
                break
            target = x
            numCount = 1
            ans.append(size)
    return ans

**Comment by xfrnk2** [comment]
말씀해주신 원칙적인 방식으로도 코딩 해봤었는데 굳이 매번 변경된 리스트의 길이를 재거나 할 필요는 없을 것 같아서 그대신 길이값(size)를 변경하는걸로 대체해 봤어요

**Comment by zrma** [comment]
@xfrnk2 Good~
