### ISSUE TITLE
빌드 실패 복구하기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#93]
@xfrnk2 

travis-ci 빌드가 엄청 많이 + 오래 실패하고 있네요.
빌드부터 복구하세요!

**Comment by xfrnk2** [comment]
@zrma 
넵 현재 오류가 나는것은 수정했어요.

**Comment by zrma** [comment]
@xfrnk2 Good!

커밋 + 푸시 하기 전에 전체 test 부터 하고 올리는 습관을 들이면 좋습니다.
