### ISSUE TITLE
values()를 사용하세요

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#98]
https://github.com/xfrnk2/1d1c/blob/14a3ac9764b9661f8a4866c06117c004cd4a24a8/hackerrank/Problem_Solving/Equalize_The_Array.py#L12

@xfrnk2 

```python
for value in box.values():
```

상황에 맞춰서 `items()`, `keys()`, `values()` 같은 메소드를 활용하면 좋습니다.

**Comment by xfrnk2** [comment]
넵 감사합니다

**Comment by zrma** [comment]
@xfrnk2 확인했어요~
