### ISSUE TITLE
테스트 케이스 명확히...

### ISSUE THREAD

**Issue by zrma** [xfrnk2/1d1c#99]
https://github.com/xfrnk2/1d1c/blob/14a3ac9764b9661f8a4866c06117c004cd4a24a8/tests/Equalize_The_Array_test.py#L11

@xfrnk2 

단순히 `연산을 잘 수행한다.` 라는 코멘트 보다는
이 테스트 케이스가 어떤 조건을 실험하고 있는 것인지 내용을 적으면 좋지 않을까요?

예를 들면

`중복 된 숫자의 경우 잘 처리한다` 라거나 `아무 값도 안 들어올 경우에도 잘 동작한다` 처럼요.

**Comment by xfrnk2** [comment]
네 명심하겠습니다~

**Comment by zrma** [comment]
@xfrnk2 Good!
